
seed: 0

data:
  path: "data/ESC-50"
  sample_rate: 8000
  train_folds: [1,2,3]
  val_folds: [4]
  test_folds: [5]
  batch_size: 8

model:
  base_filters: 32
  n_classes: 50
  optim:
    lr: 3e-4

trainer:
  max_epochs: 1
  fast_dev_run: False

defaults:
- hydra/job_logging: colorlog
- hydra/hydra_logging: colorlog

